module ImageProcessing
  class Vips
    def self.source: (path) -> instance
    def crop: (Integer, Integer, Integer, Integer) -> instance
    def convert: (string) -> instance
    def call: -> untyped
  end
end